[build]
  # Build settings
  publish = "dist"
  command = "npm run build"
  
  # Build environment variables
  environment = { NODE_ENV = "production", CI = "true", SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_APP_NAME,VITE_APP_ENV" }

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# SPA redirects - crucial for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API redirects for your Express server (if needed for serverless functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:;"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache index.html for no time (always revalidate)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache service worker for no time
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Set proper content type for manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

# Environment-specific settings
[context.production]
  command = "bun run build"
  [context.production.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "production"

[context.deploy-preview]
  command = "bun run build"
  [context.deploy-preview.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "preview"

[context.branch-deploy]
  command = "bun run build"
  [context.branch-deploy.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "development"

# Netlify Dev settings for local development
[dev]
  command = "bun run dev"
  port = 5173
  publish = "dist"
  autoLaunch = false

# Functions settings (if you plan to use Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin settings
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.8

# Form handling settings (if using Netlify Forms)
[template.environment]
  VITE_NETLIFY_FORMS = "true"